export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATRGORIES_START: 'category/FETCH_CATRGORIES_START',
    FETCH_CATRGORIES_SUCCESS: 'category/FETCH_CATRGORIES_SUCCESS',
    FETCH_CATRGORIES_FAILED: 'category/FETCH_CATRGORIES_FAILED',
}